"""Constants for the HID Climate Controller integration."""

DOMAIN = "hid_climate_controller"

ENTITY_ID_KEY = "entity_id"
FRIENDLY_NAME_KEY = "friendly_name"
DEVICE_UNIQUE_ID_KEY = "unique_id"
DEVICE_NAME_KEY = "name"
DEVICE_DEFERRED_REGISTRATION_KEY = "deferred_registration"
CONTROLLER_KEY = "controller"
CONTROLLER_ENTITY_ID_KEY = "controller_entity_id"
CONTROLLER_NAME_KEY = "controller_name"
CLIMATE_ENTITY_TYPE = "climate"
CLIMATE_KEY = "climate"
CLIMATE_ENTITY_ID_KEY = "climate_entity_id"

# Errors
BASE_ERROR_PLACEHOLDER = "base"
MULTIPLE_VALIDATION_ERRORS = "MULTIPLE_VALIDATION_ERRORS"
DEVICE_ALREADY_CONFIGURED_ERROR = "already_configured"
DEVICE_VALIDATION_UNIQUE_ID_INVALID_ERROR = "DEVICE_VALIDATION_UNIQUE_ID_INVALID_ERROR"
MQTT_DISCOVERY_STEP_INVALID_DISCOVERY_PAYLOAD_ERROR = (
    "MQTT_DISCOVERY_STEP_INVALID_DISCOVERY_PAYLOAD_ERROR"
)
MQTT_DISCOVERY_STEP_DEVICE_VALIDATION_FAILURE_ERROR = (
    "MQTT_DISCOVERY_STEP_DEVICE_VALIDATION_FAILURE_ERROR"
)
MQTT_DISCOVERY_STEP_UNKNOWN_FAILURE_ERROR = "MQTT_DISCOVERY_STEP_UNKNOWN_FAILURE_ERROR"
USER_INPUT_STEP_DEVICE_VALIDATION_FAILURE_ERROR = (
    "USER_INPUT_STEP_DEVICE_VALIDATION_FAILURE_ERROR"
)
USER_INPUT_STEP_UNKNOWN_FAILURE_ERROR = "USER_INPUT_STEP_UNKNOWN_FAILURE_ERROR"
CLIMATE_ENTITY_SELECTION_STEP_NO_AVAILABLE_ENTITIES_ERROR = (
    "CLIMATE_ENTITY_SELECTION_STEP_NO_AVAILABLE_ENTITIES_ERROR"
)
CLIMATE_ENTITY_SELECTION_STEP_VALIDATION_FAILURE_ERROR = (
    "CLIMATE_ENTITY_SELECTION_STEP_VALIDATION_FAILURE_ERROR"
)
CLIMATE_ENTITY_SELECTION_STEP_UNKNOWN_FAILURE_ERROR = (
    "CLIMATE_ENTITY_SELECTION_STEP_UNKNOWN_FAILURE_ERROR"
)
