import re

DOMAIN = "hid_climate_controller"

DEVICE_UNIQUE_ID_REGEX = re.compile(r"^HW-THID-[A-Za-z0-9]{17}$", re.IGNORECASE)
DEVICE_SW_VERSION_REGEX = re.compile(r"^\d+\.\d+\.\d+$")
DEVICE_HW_VERSION_REGEX = re.compile(r"^\d+\.\d+\.\d+$")

ENTITY_ID_KEY = "entity_id"
FRIENDLY_NAME_KEY = "friendly_name"

DEVICE_UNIQUE_ID_KEY = "unique_id"
DEVICE_NAME_KEY = "name"
DEVICE_KEY = "device"
DEVICE_MODEL_KEY = "model"
DEVICE_MANUFACTURER_KEY = "manufacturer"
DEVICE_SW_VERSION_KEY = "sw_version"
DEVICE_HW_VERSION_KEY = "hw_version"
DEVICE_DEFERRED_REGISTRATION_KEY = "deferred_registration"

CONTROLLER_KEY = "controller"
CONTROLLER_ENTITY_ID_KEY = "controller_entity_id"
CONTROLLER_NAME_KEY = "controller_name"
CLIMATE_ENTITY_TYPE = "climate"
CLIMATE_KEY = "climate"
CLIMATE_ENTITY_ID_KEY = "climate_entity_id"

# Errors
UNKNOWN_EXCEPTION_ERROR = "Unknown exception encountered. Check logs for details."

BASE_ERROR_PLACEHOLDER = "base"
REQUIRED_INPUT_ERROR = "Required"
INVALID_UNIQUE_ID_FORMAT_ERROR = "INVALID_UNIQUE_ID_FORMAT"
MULTIPLE_VALIDATION_ERRORS = "MULTIPLE_VALIDATION_ERRORS"

DEVICE_CONFIG_UPDATED = "device_config_updated"
DEVICE_ALREADY_CONFIGURED_ERROR = "already_configured"
DEVICE_VALIDATION_UNIQUE_ID_INVALID_ERROR = "DEVICE_VALIDATION_UNIQUE_ID_INVALID_ERROR"
MQTT_DISCOVERY_STEP_INVALID_DISCOVERY_PAYLOAD_ERROR = (
    "MQTT_DISCOVERY_STEP_INVALID_DISCOVERY_PAYLOAD_ERROR"
)
MQTT_DISCOVERY_STEP_DEVICE_VALIDATION_FAILURE_ERROR = (
    "MQTT_DISCOVERY_STEP_DEVICE_VALIDATION_FAILURE_ERROR"
)
MQTT_DISCOVERY_STEP_UNKNOWN_FAILURE_ERROR = "MQTT_DISCOVERY_STEP_UNKNOWN_FAILURE_ERROR"
USER_INPUT_STEP_DEVICE_VALIDATION_FAILURE_ERROR = (
    "USER_INPUT_STEP_DEVICE_VALIDATION_FAILURE_ERROR"
)
USER_INPUT_STEP_UNKNOWN_FAILURE_ERROR = "USER_INPUT_STEP_UNKNOWN_FAILURE_ERROR"
CLIMATE_ENTITY_SELECTION_STEP_NO_AVAILABLE_ENTITIES_ERROR = (
    "CLIMATE_ENTITY_SELECTION_STEP_NO_AVAILABLE_ENTITIES_ERROR"
)
CLIMATE_ENTITY_SELECTION_STEP_VALIDATION_FAILURE_ERROR = (
    "CLIMATE_ENTITY_SELECTION_STEP_VALIDATION_FAILURE_ERROR"
)
CLIMATE_ENTITY_SELECTION_STEP_UNKNOWN_FAILURE_ERROR = (
    "CLIMATE_ENTITY_SELECTION_STEP_UNKNOWN_FAILURE_ERROR"
)
