"""Constants for the HID Climate Controller integration."""

DOMAIN = "hid_climate_controller"

UNIQUE_ID_KEY = "unique_id"
ENTITY_ID_KEY = "entity_id"
FRIENDLY_NAME_KEY = "friendly_name"
CONTROLLER_KEY = "controller"
CLIMATE_KEY = "climate"
DEFERRED_REGISTRATION_KEY = "deferred_registration"

CLIMATE_ENTITY_TYPE = "climate"

GENERIC_ERROR = "GENERIC_ERROR"

MQTT_DISCOVERY_FLOW_STEP = "mqtt_discovery"
USER_FLOW_STEP = "user"
CLIMATE_ENTITY_SELECTION_FLOW_STEP = "climate_entity_selection"

DEVICE_VALIDATION_UNIQUE_ID_INVALID_ERROR = "DEVICE_VALIDATION_UNIQUE_ID_INVALID_ERROR"

MQTT_DISCOVERY_STEP_DEVICE_VALIDATION_FAILURE_ERROR = "MQTT_DISCOVERY_STEP_DEVICE_VALIDATION_FAILURE_ERROR"
MQTT_DISCOVERY_STEP_UNKNOWN_FAILURE_ERROR = "MQTT_DISCOVERY_STEP_UNKNOWN_FAILURE_ERROR"

USER_INPUT_STEP_DEVICE_VALIDATION_FAILURE_ERROR = "USER_INPUT_STEP_DEVICE_VALIDATION_FAILURE_ERROR"
USER_INPUT_STEP_UNKNOWN_FAILURE_ERROR = "USER_INPUT_STEP_UNKNOWN_FAILURE_ERROR"

CLIMATE_ENTITY_SELECTION_STEP_NO_AVAILABLE_ENTITIES_ERROR = "CLIMATE_ENTITY_SELECTION_STEP_NO_AVAILABLE_ENTITIES_ERROR"
CLIMATE_ENTITY_SELECTION_STEP_VALIDATION_FAILURE_ERROR = "CLIMATE_ENTITY_SELECTION_STEP_VALIDATION_FAILURE_ERROR"
CLIMATE_ENTITY_SELECTION_STEP_UNKNOWN_FAILURE_ERROR = "CLIMATE_ENTITY_SELECTION_STEP_UNKNOWN_FAILURE_ERROR"
